name: Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.0.0"

      - name: Install dependencies
        run: npm install
        working-directory: frontend-extension

      - name: Run format check
        run: npm run format:check
        working-directory: frontend-extension
