name: Frontend Extension Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.0.0"

      - name: Install dependencies
        run: npm install
        working-directory: frontend-extension

      - name: Build project
        run: npm run build
        working-directory: frontend-extension
