name: Mobile CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: mobile

      - name: Format check
        run: npm run format:check
        working-directory: mobile

     # - name: Run Jest tests (unit + UI)
      #  run: npm test
      #working-directory: mobile
