name: Mobile CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: mobile

      - name: Format check
        run: |
          npx prettier --check .
          npx prettier --write .
        working-directory: mobile

      - name: Run Jest tests (unit + UI)
        run: npm test
        working-directory: mobile

      #- name: Install EAS CLI
      #  run: npm install -g eas-cli

      #- name: Authenticate Expo
      #  run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      #- name: Build APK
      #  run: eas build --platform android --profile preview --non-interactive
